### PR TITLE
updating audit rules to ensure fair voting

### PR DESCRIPTION
**Pull request by itayhubara**

### CODE REVIEW

**Comment by mrmhodak** [comment]
Needs more discussion. All submitters should have same voting privileges.

**Comment by mrmhodak** [comment]
WG Feedback: Add option for appeal to the board to the rules as a standalone PR.

**Comment by psyhtest** [comment]
> If a submitter **undergoes** consecutive audits spanning two or more rounds and finds it unfair, they can appeal to the MLCommons board to ensure fairness

Should we say "is selected for" instead of "undergoes"? A submitter may find it unfair it happens for the second time and successfully appeal - then they may only undergo it only once.

> If a submitter undergoes **consecutive** audits spanning two or more rounds

Is it important for the audits to be consecutive? I'd think that being selected again even after a break could be construed as unfair.

**Comment by psyhtest** [comment]
> If a submitter chosen for an audit finds it unfair, they can appeal to the MLCommons Executive Director to ensure fairness.

**Review by mrmhodak — APPROVED** [review]

**Pull request merged**
