### PR TITLE
Add audit guidelines

### PR DESCRIPTION
**Pull request by nvzhihanj**

### CODE REVIEW

**Comment by rnaidu02** [comment]
@tjablin  @psyhtest Can you review and provide your comments by next week?

**Comment by tjablin** [comment]
This seems very reasonable to me.

**Comment by nv-ananjappa** [comment]
@rnaidu02 Could you merge since all review comments have been addressed?

**Comment by nvzhihanj** [comment]
@rnaidu02 kindly checking again for the review/approval, thanks.

**Comment by nv-ananjappa** [comment]
@tjablin Could you please review and see if any other changes are required?

**Review by tjablin — APPROVED** [review]

**Pull request merged**
