### PR TITLE
Clarify DLRM text

### PR DESCRIPTION
**Pull request by tjablin**
The DLRM FAQ is a source of confusion. Simplify.

### CODE REVIEW

**Comment by christ1ne** [comment]
@mnaumovfb  can you help review? Thanks!

**Comment by cayleyhamilton** [comment]
The text would be clearer, if the 'user-item pair' is defined.  The criteo dataset does not define it either. 

Perhaps, we can say  'user-item pair' corresponds to 1 row in the Criteo dataset without the label -- ie the user-item pair is represented by 13 count features and 26 categorical features.

**Comment by mnaumovfb** [comment]
Hmmm, I'm not sure I'm completely onboard with the change in wording. The original version provides a wealth of information about the distribution, it's implementation and how to call it. It's true that it's a bit verbose as it follows the evolution of the implementation and different options available to the users. However, the new version perhaps goes to far, it is very short and does not contain the same information.

Maybe we can find a compromise by using the new wording, but leaving some of the old info in the background/more details under it.

**Comment by tjablin** [comment]
I re-added a lot of supplemental information while trying to clarify what is necessary for compliance. PTAL.

**Comment by mnaumovfb** [comment]
The new wording looks good to me. Thank you.

**Comment by tjablin** [comment]
NP!

**Pull request merged**
