### PR TITLE
Updates on measured components and power delivery path

### PR DESCRIPTION
**Pull request by s-idgunji**
Added changes for review in upcoming Power WG meeting.   Two edits 
1) That the power measurements are done on all components sensitized by loadgen including the processor on which loadgen runs
2)  Power delivery should not have any battery or alternate energy storage augmenting wall power

### CODE REVIEW

**Comment by s-idgunji** [comment]
Updates for v1.1 to be reviewed in Power WG on 08/04/21

**Comment by araghun** [comment]
We can review this tomorrow in the meeting. Thanks, Sachin.

**Comment by s-idgunji** [comment]
> We can review this tomorrow in the meeting. Thanks, Sachin.

Sounds good.  The link for the doc itself  -
https://github.com/mlcommons/inference_policies/blob/73a198e7ca51cce6609c2c49ad1e1ef3ebea0d8e/power_measurement.adoc

**Review by araghun — APPROVED** [review]
Checks look good.

**Review by araghun — APPROVED** [review]

**Comment by araghun** [comment]
@TheKanter Can you please help approve/merge it. I approved it, but for some reason the merging is blocked.

**Review by TheKanter — APPROVED** [review]

**Pull request merged**
